# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[󱞩](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# A continuation prompt that displays two filled in arrows
continuation_prompt = '▶▶ '

[status]
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
pipestatus = true
map_symbol = true
disabled = false

#format = """
#[](#9A348E)\
#$os\
#$username\
#[](bg:#a63851 fg:#9A348E)\
#$directory\
#[](fg:#a63851 bg:#99411f)\
#$git_branch\
#$git_status\
#[](fg:#99411f bg:#386d8a)\
#$c\
#$elixir\
#$elm\
#$golang\
#$gradle\
#$haskell\
#$java\
#$julia\
#$nodejs\
#$nim\
#$rust\
#$scala\
#[](fg:#386d8a bg:#06969A)\
#$docker_context\
#[](fg:#06969A bg:#33658A)\
#$time\
#[ ](fg:#33658A)\
#"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
#style_user = "bg:#9A348E"
#style_root = "bg:#9A348E"
format = '[$user ]($style)'
disabled = true

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
#style = "bg:#9A348E"
disabled = true # Disabled by default

[cmd_duration]
min_time = 500
format = 'underwent [$duration](bold yellow)'

[directory]
#style = "bg:#a63851"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[aws]
disabled = true
symbol = "  "

[gcloud]
disabled = true

[c]
symbol = " "
#style = "bg:#386d8a"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
#style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[git_branch]
symbol = ""
#style = "bg:#99411f"
format = '[ $symbol $branch ]($style)'

[git_status]
#style = "bg:#99411f"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
#style = "bg:#386d8a"
format = '[ $symbol ]($style)'

[nix_shell]
disabled = false
impure_msg = '[impure shell](bold red)'
pure_msg = '[pure shell](bold green)'
unknown_msg = '[unknown shell](bold yellow)'
format = 'via [☃️ $state( \($name\))](bold blue) '

[rust]
symbol = ""
#style = "bg:#386d8a"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
#style = "bg:#33658A"
format = '[ ♥ $time ]($style)'
